name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' # ou la version que tu utilises

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test # Assure-toi que cette commande fonctionne pour tes tests
